/*
	DBSeLayerPortExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "DBSeLayerPortExample.h"
#import "DBSeLayerPort.h"

@implementation DBSeLayerPortExample

- (void)run {
	// Create the service
	DBSeLayerPort* service = [DBSeLayerPort service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns DBdeleteResponse*. 
	[service deleteFeature:self action:@selector(deleteFeatureHandler:) arg0: [[DBdeleteObject alloc] init]];

	// Returns DBqueryResponse*. 
	[service getFeature:self action:@selector(getFeatureHandler:) arg0: [[DBqueryObject alloc] init]];

	// Returns DBfeature*. 
	[service getFeatureByBsm:self action:@selector(getFeatureByBsmHandler:) layerName: @"" bsm: @""];

	// Returns DBseLayerVO*. 
	[service getLayer:self action:@selector(getLayerHandler:) arg0: @""];

	// Returns DBseLayerVO*. 
	[service getLayers:self action:@selector(getLayersHandler:)];

	// Returns DBinsertResponse*. 
	[service insertFeature:self action:@selector(insertFeatureHandler:) arg0: [[DBinsertObject alloc] init]];

	// Returns DBupdateResponse*. 
	[service updateFeature:self action:@selector(updateFeatureHandler:) arg0: [[DBupdateObject alloc] init]];
}

	

// Handle the response from deleteFeature.
		
- (void) deleteFeatureHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the DBdeleteResponse* result
		DBdeleteResponse* result = (DBdeleteResponse*)value;
	NSLog(@"deleteFeature returned the value: %@", result);
			
}
	

// Handle the response from getFeature.
		
- (void) getFeatureHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the DBqueryResponse* result
		DBqueryResponse* result = (DBqueryResponse*)value;
	NSLog(@"getFeature returned the value: %@", result);
			
}
	

// Handle the response from getFeatureByBsm.
		
- (void) getFeatureByBsmHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the DBfeature* result
		DBfeature* result = (DBfeature*)value;
	NSLog(@"getFeatureByBsm returned the value: %@", result);
			
}
	

// Handle the response from getLayer.
		
- (void) getLayerHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the DBseLayerVO* result
		DBseLayerVO* result = (DBseLayerVO*)value;
	NSLog(@"getLayer returned the value: %@", result);
			
}
	

// Handle the response from getLayers.
		
- (void) getLayersHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the DBseLayerVO* result
		DBseLayerVO* result = (DBseLayerVO*)value;
	NSLog(@"getLayers returned the value: %@", result);
			
}
	

// Handle the response from insertFeature.
		
- (void) insertFeatureHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the DBinsertResponse* result
		DBinsertResponse* result = (DBinsertResponse*)value;
	NSLog(@"insertFeature returned the value: %@", result);
			
}
	

// Handle the response from updateFeature.
		
- (void) updateFeatureHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the DBupdateResponse* result
		DBupdateResponse* result = (DBupdateResponse*)value;
	NSLog(@"updateFeature returned the value: %@", result);
			
}
	

@end
		