/*
	DB2GoverDeciServerServiceExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface DB2GoverDeciServerServiceExample : NSObject {
}
-(void)run;
@end
		