/*
	DB2GoverDeciServerServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "DB2GoverDeciServerServiceExample.h"
#import "DB2GoverDeciServerService.h"

@implementation DB2GoverDeciServerServiceExample

- (void)run {
	// Create the service
	DB2GoverDeciServerService* service = [DB2GoverDeciServerService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
//	[service CommonService:self action:@selector(CommonServiceHandler:) arg0: @""];

}

	

/*
// Handle the response from CommonService.
		
- (void) CommonServiceHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"CommonService returned the value: %@", result);
			
}
*/

@end
		